// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type Metric =
  | '*'
  | 'avg_build_time'
  | 'cpu_usage'
  | 'ram_indexing_usage'
  | 'ram_search_usage'
  | 'ssd_usage';
