// index methods that should be implemented, `true` if they are

const apiMethods = {
  addApiKey: false,
  addObject: false,
  addObjects: false,
  batch: true,
  batchRules: false,
  batchSynonyms: false,
  browse: true,
  browseAll: false,
  browseFrom: true,
  clearRules: false,
  clearSynonyms: false,
  deleteApiKey: false,
  deleteByQuery: false,
  deleteObject: false,
  deleteObjects: false,
  deleteRule: false,
  deleteSynonym: false,
  getApiKey: false,
  getObject: true,
  getObjects: true,
  getRule: false,
  getSettings: false,
  getSynonym: false,
  listApiKeys: false,
  partialUpdateObject: false,
  partialUpdateObjects: false,
  saveObject: false,
  saveObjects: false,
  saveRule: false,
  saveSynonym: false,
  search: true,
  searchForFacetValues: false,
  searchRules: false,
  searchSynonyms: false,
  setSettings: false,
  similarSearch: false,
  updateApiKey: false,
  waitTask: true,
};

const requesterMethods = {
  clearCache: false,
};
