// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { VariantSettings } from './variantSettings';

/**
 * Captured settings of an A/B test.
 */
export type ABTestSettingsResponse = {
  /**
   * Captured settings for each variant of the A/B test.
   */
  abtestSettings: Array<VariantSettings>;

  /**
   * Whether another active A/B test is using the control index.
   */
  controlIndexInUse: boolean;
};
