// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * A/B test statistical analysis method. When omitted, the test is treated as `frequentist`. The server doesn\'t write a default value back to the configuration.
 */
export type AnalysisMethod = 'bayesian' | 'frequentist';
