// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { MetricEvidence } from './metricEvidence';

/**
 * Bayesian inference results for this variant metric. Omitted when Bayesian results aren\'t requested or no Bayesian result is available for this metric. Individual inference fields can be omitted when their values aren\'t available.
 */
export type BayesianMetricResult = {
  /**
   * Probability that this variant is better than the control.
   */
  probabilityToBeBetter?: number | undefined;

  /**
   * Lower bound of the 95% credible interval for the relative effect (variant/control minus 1).
   */
  relativeEffectCILow?: number | undefined;

  /**
   * Upper bound of the 95% credible interval for the relative effect (variant/control minus 1).
   */
  relativeEffectCIHigh?: number | undefined;

  evidence?: MetricEvidence | undefined;
};
