// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { AddABTestsVariant } from './addABTestsVariant';
import type { EstimateConfiguration } from './estimateConfiguration';

export type EstimateABTestRequest = {
  configuration: EstimateConfiguration;

  /**
   * A/B test variants.
   */
  variants: Array<AddABTestsVariant>;
};
