// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Boolean filter applied to the A/B test population. Each filter targets a boolean metric and decides whether to include (true) or exclude (false) matching records.
 */
export type MetricsFilter = {
  /**
   * Metric domain (for example `abtesting`, `personalization`).
   */
  domain: string;

  /**
   * Public metric name.
   */
  name: string;

  /**
   * Whether the experiment should record the effects of this filter.
   */
  trackEffects?: boolean | undefined;

  /**
   * If true, keep items that match the filter; if false, exclude them.
   */
  includes?: boolean | undefined;
};
