// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { MetricResult } from './metricResult';

export type MetricDate = {
  /**
   * Date where the metric was updated, in RFC 3339 format.
   */
  date?: string | undefined;

  /**
   * All ABTest metrics that were defined during test creation.
   */
  metrics?: Array<MetricResult> | undefined;
};
