// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Defines a metric to be retrieved during an A/B test.
 */
export type ParametersMetric = {
  /**
   * Name of the metric.
   */
  name: string;

  /**
   * Dimension of the metric, for example, in case of a revenue metric it could be USD, EUR...
   */
  dimension?: string | undefined;
};
