// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ModelsToRetrieveParam } from './modelsToRetrieveParam';
import type { TypesToRetrieveParam } from './typesToRetrieveParam';

export type AllParams = ModelsToRetrieveParam & TypesToRetrieveParam;
