// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type DeleteModelInstanceResponse = {
  /**
   * The ID of the model.
   */
  modelID: string;

  /**
   * The date until which you can safely consider the data as being deleted.
   */
  deletedUntil: string;
};
