// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { SegmentFunnelStageFilter } from './segmentFunnelStageFilter';

/**
 * Operand for funnel stage model predictions.
 */
export type SegmentOperandFunnelStage = {
  name: string;

  filters: SegmentFunnelStageFilter[];
};
