openapi: 3.0.2
info:
  title: Search API
  description: API powering the Search feature of Algolia.
  version: 0.1.0
servers:
  - url: https://{appId}-1.algolianet.com
    variables:
      appId:
        default: test
  - url: https://{appId}-2.algolianet.com
    variables:
      appId:
        default: test
  - url: https://{appId}-3.algolianet.com
    variables:
      appId:
        default: test
  - url: https://{appId}-dsn.algolianet.com
    variables:
      appId:
        default: test
paths:
  # We can add this one later, as it requires the init method
  # /1/indexes/{indexName}/query:
  #   $ref: "./paths/indexes/search.yml"
  /1/indexes/*/queries:
    $ref: "./paths/indexes/searchMulti.yml"
  /1/indexes/{indexName}:
    $ref: "./paths/indexes/saveObject.yml"
  /1/indexes/{indexName}/batch:
    $ref: "./paths/indexes/batch.yml"
