// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type BaseGetApiKeyResponse = {
  /**
   * API key.
   */
  value?: string;

  /**
   * Timestamp of creation in milliseconds in [Unix epoch time](https://wikipedia.org/wiki/Unix_time).
   */
  createdAt: number;
};
