// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { BatchDictionaryEntriesRequest } from './batchDictionaryEntriesRequest';

/**
 * `batchDictionaryEntries` parameters.
 */
export type BatchDictionaryEntriesParams = {
  /**
   * Incidates whether to replace all custom entries in the dictionary with the ones sent with this request.
   */
  clearExistingDictionaryEntries?: boolean;

  /**
   * Operations to batch.
   */
  requests: BatchDictionaryEntriesRequest[];
};
