// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Assign userID parameters.
 */
export type BatchAssignUserIdsParams = {
  /**
   * Name of the cluster.
   */
  cluster: string;

  /**
   * UserIDs to assign. Note you cannot move users with this method.
   */
  users: string[];
};
