// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Redirect to a virtual replica index.  This consequence is only valid for rules with `scope: redirect`.
 */
export type ConsequenceRedirect = {
  /**
   * Name of the virtual replica index to redirect searches to.
   */
  indexName: string;
};
