// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ConsequenceHide } from './consequenceHide';
import type { ConsequenceParams } from './consequenceParams';
import type { ConsequenceRedirect } from './consequenceRedirect';
import type { Promote } from './promote';

/**
 * Effect of the rule.  For more information, see [Consequences](https://www.algolia.com/doc/guides/managing-results/rules/rules-overview/#consequences).
 */
export type Consequence = {
  params?: ConsequenceParams | undefined;

  /**
   * Records you want to pin to a specific position in the search results.  You can promote up to 300 records, either individually, or as groups of up to 100 records each.
   */
  promote?: Array<Promote> | undefined;

  /**
   * Determines whether promoted records must also match active filters for the consequence to apply.  This ensures user-applied filters take priority and irrelevant matches aren\'t shown. For example, if you promote a record with `color: red` but the user filters for `color: blue`, the \"red\" record won\'t be shown.  > In the Algolia dashboard, when you use the **Pin an item** consequence, `filterPromotes` appears as the checkbox: **Pinned items must match active filters to be displayed.** For examples, see [Promote results with rules](https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/promote-hits/#promote-results-matching-active-filters).
   */
  filterPromotes?: boolean | undefined;

  /**
   * Records you want to hide from the search results.
   */
  hide?: Array<ConsequenceHide> | undefined;

  redirect?: ConsequenceRedirect | undefined;

  /**
   * A JSON object with custom data that will be appended to the `userData` array in the response. This object isn\'t interpreted by the API and is limited to 1&nbsp;kB of minified JSON.
   */
  userData?: Record<string, unknown> | undefined;
};
