// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ConsequenceHide } from './consequenceHide';
import type { ConsequenceParams } from './consequenceParams';
import type { Promote } from './promote';

/**
 * [Consequences](https://www.algolia.com/doc/guides/managing-results/rules/rules-overview/#consequences) of a rule.
 */
export type Consequence = {
  params?: ConsequenceParams;

  /**
   * Records to promote.
   */
  promote?: Promote[];

  /**
   * Only use in combination with the `promote` consequence. When `true`, promoted results will be restricted to match the filters of the current search. When `false`, the promoted results will show up regardless of the filters.
   */
  filterPromotes?: boolean;

  /**
   * Records to hide. By default, you can hide up to 50 records per rule.
   */
  hide?: ConsequenceHide[];

  /**
   * Custom JSON object that will be appended to the userData array in the response. This object isn\'t interpreted by the API. It\'s limited to 1kB of minified JSON.
   */
  userData?: any | null;
};
