// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { FetchedIndexAbTestTarget } from './fetchedIndexAbTestTarget';
import type { FetchedIndexAbTestVariant } from './fetchedIndexAbTestVariant';

/**
 * A/B test metadata. Only present if the index is part of an active A/B test.
 */
export type FetchedIndexAbTest = {
  /**
   * A/B test ID.
   */
  id: number;

  /**
   * A/B test schema version. Only present for v2 and later tests.
   */
  version?: number | undefined;

  /**
   * A/B test type. Only present for v2 and later tests. Currently always `index-configuration`.
   */
  type?: string | undefined;

  target?: FetchedIndexAbTestTarget | undefined;

  /**
   * A/B test variants.
   */
  variants: Array<FetchedIndexAbTestVariant>;
};
