// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * The search mode that the index will use to query for results.
 */
export type Mode = 'keywordSearch' | 'neuralSearch';
