// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type MultipleBatchResponse = {
  /**
   * List of tasksIDs per index.
   */
  taskID: Record<string, number>;

  /**
   * List of objectID.
   */
  objectIDs: string[];
};
