// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { MixedSearchFilters } from './mixedSearchFilters';

/**
 * Create filters to boost or demote records.   Records that match the filter are ranked higher for positive and lower for negative optional filters. In contrast to regular filters, records that don\'t match the optional filter are still included in the results, only their ranking is affected.
 */
export type OptionalFilters = MixedSearchFilters[] | string;
