// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { AutoFilteringResult } from './autoFilteringResult';
import type { CategoryPrediction } from './categoryPrediction';
import type { QueryCategorizationType } from './queryCategorizationType';

/**
 * Query Categorization prediction returned by the AI model. This field is empty when the model cannot categorize the query. See [Query Categorization](https://www.algolia.com/doc/guides/algolia-ai/query-categorization/).
 */
export type QueryCategorization = {
  /**
   * Processed and normalized version of the original search query.
   */
  normalizedQuery?: string | undefined;

  /**
   * Number of times this normalized query was observed during the training window.
   */
  count?: number | undefined;

  type?: QueryCategorizationType | undefined;

  /**
   * List of category predictions with confidence levels.
   */
  categories?: Array<CategoryPrediction> | undefined;

  autofiltering?: AutoFilteringResult | undefined;
};
