// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { QueryCategorization } from './queryCategorization';

/**
 * AI-generated metadata returned alongside search results. Present when Algolia AI features such as [Query Categorization](https://www.algolia.com/doc/guides/algolia-ai/query-categorization/) are enabled.
 */
export type ResponseExtensions = {
  queryCategorization?: QueryCategorization | undefined;
};
