// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type SaveObjectResponse = {
  createdAt: string;

  /**
   * TaskID of the task to wait for.
   */
  taskID: number;

  /**
   * Unique identifier of the object.
   */
  objectID?: string;
};
