// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { SynonymType } from './synonymType';

export type SearchSynonymsParams = {
  /**
   * Text to search for in an index.
   */
  query?: string;

  type?: SynonymType;

  /**
   * Page to retrieve (the first page is `0`, not `1`).
   */
  page?: number;

  /**
   * Number of hits per page.
   */
  hitsPerPage?: number;
};
