// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Search parameter.
 */
export type SearchDictionaryEntriesParams = {
  /**
   * Search query.
   */
  query: string;

  /**
   * Page of search results to retrieve.
   */
  page?: number;

  /**
   * Number of hits per page.
   */
  hitsPerPage?: number;

  /**
   * ISO code of a [supported language](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/handling-natural-languages-nlp/in-depth/supported-languages/).
   */
  language?: string;
};
