// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { BaseSearchResponse } from './baseSearchResponse';
import type { SearchPagination } from './searchPagination';

/**
 * Partial search response returned when the `responseFields` parameter excludes fields like `hits`. Contains all possible search response properties but none are required, so it acts as an unconditional fallback during oneOf deserialization.
 */
export type SearchResponsePartial<T = Record<string, unknown>> = BaseSearchResponse &
  SearchPagination & { [key: string]: any };
