// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Response, taskID, unique object identifier, and an update timestamp.
 */
export type UpdatedAtWithObjectIdResponse = {
  /**
   * Unique identifier of a task. A successful API response means that a task was added to a queue. It might not run immediately. You can check the task\'s progress with the `task` operation and this `taskID`.
   */
  taskID?: number;

  /**
   * Timestamp of the last update in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
   */
  updatedAt?: string;

  /**
   * Unique object identifier.
   */
  objectID?: string;
};
