// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ClickEvent } from './clickEvent';

/**
 * Click event after an Algolia request.  Use this event to track when users click items in the search results. If you\'re building your category pages with Algolia, you\'ll also use this event.
 */
export type ClickedObjectIDsAfterSearch = {
  /**
   * Can contain up to 64 ASCII characters.   Consider naming events consistently—for example, by adopting Segment\'s [object-action](https://segment.com/academy/collecting-data/naming-conventions-for-clean-data/#the-object-action-framework) framework.
   */
  eventName: string;

  eventType: ClickEvent;

  /**
   * Name of the Algolia index.
   */
  index: string;

  /**
   * List of object identifiers for items of an Algolia index.
   */
  objectIDs: string[];

  /**
   * Position of the clicked objects in the search results.  The first search result has a position of 1 (not 0). You must provide 1 `position` for each `objectID`.
   */
  positions: number[];

  /**
   * Unique identifier for a search query.  The query ID is required for events related to search or browse requests. If you add `clickAnalytics: true` as a search request parameter, the query ID is included in the API response.
   */
  queryID: string;

  /**
   * Anonymous or pseudonymous user identifier.   > **Note**: Never include personally identifiable information in user tokens.
   */
  userToken: string;

  /**
   * Time of the event in milliseconds in [Unix epoch time](https://wikipedia.org/wiki/Unix_time). By default, the Insights API uses the time it receives an event as its timestamp.
   */
  timestamp?: number;
};
