// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * The response of the Insights API.
 */
export type EventsResponse = {
  /**
   * Details about the response, such as error messages.
   */
  message?: string;

  /**
   * The HTTP status code of the response.
   */
  status?: number;
};
