// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { Discount } from './discount';
import type { Price } from './price';

export type ObjectDataAfterSearch = {
  /**
   * Unique identifier for a search query, used to track purchase events with multiple records that originate from different searches.
   */
  queryID?: string;

  price?: Price;

  /**
   * The quantity of a product that has been purchased or added to the cart. The total value of a purchase is the sum of `quantity` multiplied with the `price` for each purchased item.
   */
  quantity?: number;

  discount?: Discount;
};
