// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Total monetary value of this event in units of `currency`. This should be equal to the sum of `price` times `quantity`.
 */
export type Value = number | string;
