// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type EventScoring = {
  /**
   * The score for the event.
   */
  score: number;

  /**
   * The name of the event.
   */
  eventName: string;

  /**
   * The type of the event.
   */
  eventType: string;
};
