// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { EventType } from './eventType';

export type EventScoring = {
  /**
   * Event score.
   */
  score: number;

  /**
   * Event name.
   */
  eventName: string;

  eventType: EventType;
};
