import { createNullCache } from '@algolia/cache-common';
import {
  addABTest,
  createAnalyticsClient,
  deleteABTest,
  getABTest,
  getABTests,
  stopABTest,
} from '@algolia/client-analytics';
import { version } from '@algolia/client-common';
import {
  addApiKey,
  assignUserID,
  assignUserIDs,
  batch,
  browseObjects,
  browseRules,
  browseSynonyms,
  clearObjects,
  clearRules,
  clearSynonyms,
  copyIndex,
  copySettings,
  copySynonyms,
  createSearchClient,
  deleteApiKey,
  deleteBy,
  deleteIndex,
  deleteObject,
  deleteObjects,
  deleteRule,
  deleteSynonym,
  exists,
  findObject,
  generateSecuredApiKey,
  getApiKey,
  getLogs,
  getObject,
  getObjectPosition,
  getObjects,
  getPersonalizationStrategy,
  getRule,
  getSecuredApiKeyRemainingValidity,
  getSettings,
  getSynonym,
  getTopUserIDs,
  getUserID,
  initIndex,
  listApiKeys,
  listClusters,
  listIndices,
  listUserIDs,
  moveIndex,
  multipleBatch,
  multipleGetObjects,
  multipleQueries,
  multipleSearchForFacetValues,
  partialUpdateObject,
  partialUpdateObjects,
  removeUserID,
  replaceAllObjects,
  replaceAllRules,
  replaceAllSynonyms,
  restoreApiKey,
  saveObject,
  saveObjects,
  saveRule,
  saveRules,
  saveSynonym,
  saveSynonyms,
  search,
  searchForFacetValues,
  searchRules,
  searchSynonyms,
  searchUserIDs,
  setPersonalizationStrategy,
  setSettings,
  updateApiKey,
  waitTask,
} from '@algolia/client-search';
import { createNullLogger } from '@algolia/logger-common';
import { createNodeHttpRequester } from '@algolia/requester-node-http';
import { createUserAgent } from '@algolia/transporter';

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export default function algoliasearch(appId: string, apiKey: string) {
  const clientOptions = {
    appId,
    apiKey,
    timeouts: {
      read: 2,
      write: 30,
    },
    requester: createNodeHttpRequester(),
    logger: createNullLogger(),
    responsesCache: createNullCache(),
    requestsCache: createNullCache(),
    hostsCache: createNullCache(),
    userAgent: createUserAgent(version).add({
      segment: 'Node.js',
      version: process.versions.node,
    }),
  };

  return createSearchClient({
    ...clientOptions,
    methods: {
      search: multipleQueries,
      searchForFacetValues: multipleSearchForFacetValues,
      multipleBatch,
      multipleGetObjects,
      multipleQueries,
      copyIndex,
      copySettings,
      copySynonyms,
      moveIndex,
      getPersonalizationStrategy,
      setPersonalizationStrategy,
      listIndices,
      getLogs,
      listClusters,
      multipleSearchForFacetValues,
      getApiKey,
      addApiKey,
      listApiKeys,
      updateApiKey,
      deleteApiKey,
      restoreApiKey,
      assignUserID,
      assignUserIDs,
      getUserID,
      searchUserIDs,
      listUserIDs,
      getTopUserIDs,
      removeUserID,
      generateSecuredApiKey,
      getSecuredApiKeyRemainingValidity,
      initIndex: base => (indexName: string) => {
        return initIndex(base)(indexName, {
          methods: {
            batch,
            delete: deleteIndex,
            getObject,
            getObjects,
            saveObject,
            saveObjects,
            search,
            searchForFacetValues,
            waitTask,
            setSettings,
            getSettings,
            partialUpdateObject,
            partialUpdateObjects,
            deleteObject,
            deleteObjects,
            deleteBy,
            clearObjects,
            browseObjects,
            getObjectPosition,
            findObject,
            exists,
            saveSynonym,
            saveSynonyms,
            getSynonym,
            searchSynonyms,
            browseSynonyms,
            deleteSynonym,
            clearSynonyms,
            replaceAllObjects,
            replaceAllSynonyms,
            searchRules,
            getRule,
            deleteRule,
            saveRule,
            saveRules,
            replaceAllRules,
            browseRules,
            clearRules,
          },
        });
      },
      initAnalytics: () => (region?: string) => {
        return createAnalyticsClient({
          ...clientOptions,
          region,
          methods: {
            addABTest,
            getABTest,
            getABTests,
            stopABTest,
            deleteABTest,
          },
        });
      },
    },
  });
}

export type SearchClient = ReturnType<typeof algoliasearch>;
export type SearchIndex = ReturnType<SearchClient['initIndex']>;
export type AnalyticsClient = ReturnType<SearchClient['initAnalytics']>;

export * from '../types';
