// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { BannerImageUrl } from './bannerImageUrl';

/**
 * image of a search banner.
 */
export type BannerImage = {
  urls?: Array<BannerImageUrl>;

  title?: string;
};
