// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { RecommendedForYouModel } from './recommendedForYouModel';
import type { RecommendedForYouQueryParameters } from './recommendedForYouQueryParameters';

export type BaseRecommendedForYouQuery = {
  model: RecommendedForYouModel;

  queryParameters?: RecommendedForYouQueryParameters;

  fallbackParameters?: RecommendedForYouQueryParameters;
};
