// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Records to promote.
 */
export type PromoteObjectIDs = {
  /**
   * Unique identifiers of the records to promote.
   */
  objectIDs: string[];

  /**
   * The position to promote the records to. If you pass objectIDs, the records are placed at this position as a group. For example, if you pronmote four objectIDs to position 0, the records take the first four positions.
   */
  position: number;
};
