// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { HighlightResult } from './highlightResult';
import type { RankingInfo } from './rankingInfo';
import type { SnippetResult } from './snippetResult';

/**
 * Recommend hit.
 */
export type RecommendHit = Record<string, any> & {
  /**
   * Unique object identifier.
   */
  objectID: string;

  /**
   * Show highlighted section and words matched on a query.
   */
  _highlightResult?: Record<string, HighlightResult>;

  /**
   * Snippeted attributes show parts of the matched attributes. Only returned when attributesToSnippet is non-empty.
   */
  _snippetResult?: Record<string, SnippetResult>;

  _rankingInfo?: RankingInfo;

  _distinctSeqID?: number;

  /**
   * Recommendation score.
   */
  _score: number;
};
