// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { BaseIndexSettings } from './baseIndexSettings';
import type { BaseRecommendIndexSettings } from './baseRecommendIndexSettings';

/**
 * Index settings.
 */
export type RecommendIndexSettings = BaseIndexSettings & BaseRecommendIndexSettings;
