// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Trending facet values model.  This model recommends trending facet values for the specified facet attribute.
 */
export type TrendingFacetsModel = 'trending-facets';
