// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Trending facet hit.
 */
export type TrendingFacetHit = {
  /**
   * Recommendation score.
   */
  _score: number;

  /**
   * Facet name for trending models.
   */
  facetName: string;

  /**
   * Facet value for trending models.
   */
  facetValue: string;
};
