// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { GetUsage400ResponseErrorErrorsInner } from './getUsage400ResponseErrorErrorsInner';

export type GetUsage400ResponseError = {
  code?: string;

  message?: string;

  errors?: GetUsage400ResponseErrorErrorsInner[];
};
