// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { Direction } from './direction';
import type { OrderBy } from './orderBy';

/**
 * Properties for the `del` method.
 */
export type DelProps = {
  /**
   * Path of the endpoint, anything after \"/1\" must be specified.
   */
  path: string;
  /**
   * Query parameters to apply to the current query.
   */
  parameters?: Record<string, any>;
};

/**
 * Properties for the `get` method.
 */
export type GetProps = {
  /**
   * Path of the endpoint, anything after \"/1\" must be specified.
   */
  path: string;
  /**
   * Query parameters to apply to the current query.
   */
  parameters?: Record<string, any>;
};

/**
 * Properties for the `getAverageClickPosition` method.
 */
export type GetAverageClickPositionProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getClickPositions` method.
 */
export type GetClickPositionsProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getClickThroughRate` method.
 */
export type GetClickThroughRateProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getConversationRate` method.
 */
export type GetConversationRateProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getNoClickRate` method.
 */
export type GetNoClickRateProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getNoResultsRate` method.
 */
export type GetNoResultsRateProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getSearchesCount` method.
 */
export type GetSearchesCountProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getSearchesNoClicks` method.
 */
export type GetSearchesNoClicksProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Number of records to return (page size).
   */
  limit?: number;
  /**
   * Position of the starting record. Used for paging. 0 is the first record.
   */
  offset?: number;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getSearchesNoResults` method.
 */
export type GetSearchesNoResultsProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Number of records to return (page size).
   */
  limit?: number;
  /**
   * Position of the starting record. Used for paging. 0 is the first record.
   */
  offset?: number;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getStatus` method.
 */
export type GetStatusProps = {
  /**
   * Index name to target.
   */
  index: string;
};

/**
 * Properties for the `getTopCountries` method.
 */
export type GetTopCountriesProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Number of records to return (page size).
   */
  limit?: number;
  /**
   * Position of the starting record. Used for paging. 0 is the first record.
   */
  offset?: number;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getTopFilterAttributes` method.
 */
export type GetTopFilterAttributesProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * User query.
   */
  search?: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Number of records to return (page size).
   */
  limit?: number;
  /**
   * Position of the starting record. Used for paging. 0 is the first record.
   */
  offset?: number;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getTopFilterForAttribute` method.
 */
export type GetTopFilterForAttributeProps = {
  /**
   * Attribute name.
   */
  attribute: string;
  /**
   * Index name to target.
   */
  index: string;
  /**
   * User query.
   */
  search?: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Number of records to return (page size).
   */
  limit?: number;
  /**
   * Position of the starting record. Used for paging. 0 is the first record.
   */
  offset?: number;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getTopFiltersNoResults` method.
 */
export type GetTopFiltersNoResultsProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * User query.
   */
  search?: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Number of records to return (page size).
   */
  limit?: number;
  /**
   * Position of the starting record. Used for paging. 0 is the first record.
   */
  offset?: number;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getTopHits` method.
 */
export type GetTopHitsProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * User query.
   */
  search?: string;
  /**
   * Whether to include [click and conversion](https://www.algolia.com/doc/guides/sending-events/getting-started/) rates for a search.
   */
  clickAnalytics?: boolean;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Number of records to return (page size).
   */
  limit?: number;
  /**
   * Position of the starting record. Used for paging. 0 is the first record.
   */
  offset?: number;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getTopSearches` method.
 */
export type GetTopSearchesProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Whether to include [click and conversion](https://www.algolia.com/doc/guides/sending-events/getting-started/) rates for a search.
   */
  clickAnalytics?: boolean;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Reorder the results.
   */
  orderBy?: OrderBy;
  /**
   * Sorting direction of the results: ascending or descending.
   */
  direction?: Direction;
  /**
   * Number of records to return (page size).
   */
  limit?: number;
  /**
   * Position of the starting record. Used for paging. 0 is the first record.
   */
  offset?: number;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `getUsersCount` method.
 */
export type GetUsersCountProps = {
  /**
   * Index name to target.
   */
  index: string;
  /**
   * Start date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  startDate?: string;
  /**
   * End date (a string in the format `YYYY-MM-DD`) of the period to analyze.
   */
  endDate?: string;
  /**
   * Filter analytics on the [`analyticsTags`](https://www.algolia.com/doc/api-reference/api-parameters/analyticsTags/) set at search time. Multiple tags can be combined with the operators OR and AND. If a tag contains characters like spaces or parentheses, it must be URL-encoded.
   */
  tags?: string;
};

/**
 * Properties for the `post` method.
 */
export type PostProps = {
  /**
   * Path of the endpoint, anything after \"/1\" must be specified.
   */
  path: string;
  /**
   * Query parameters to apply to the current query.
   */
  parameters?: Record<string, any>;
  /**
   * Parameters to send with the custom request.
   */
  body?: Record<string, any>;
};

/**
 * Properties for the `put` method.
 */
export type PutProps = {
  /**
   * Path of the endpoint, anything after \"/1\" must be specified.
   */
  path: string;
  /**
   * Query parameters to apply to the current query.
   */
  parameters?: Record<string, any>;
  /**
   * Parameters to send with the custom request.
   */
  body?: Record<string, any>;
};
