// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ConversionRateEvent } from './conversionRateEvent';

export type GetConversationRateResponse = {
  /**
   * [Click-through rate (CTR)](https://www.algolia.com/doc/guides/search-analytics/concepts/metrics/#click-through-rate).
   */
  rate: number;

  /**
   * Number of tracked searches. This is the number of search requests where the `clickAnalytics` parameter is `true`.
   */
  trackedSearchCount: number;

  /**
   * Number of converted clicks.
   */
  conversionCount: number;

  /**
   * Conversion events.
   */
  dates: ConversionRateEvent[];
};
