// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ConversionRateEvent } from './conversionRateEvent';

export type GetConversationRateResponse = {
  /**
   * The click-through rate.
   */
  rate: number;

  /**
   * The number of tracked search click.
   */
  trackedSearchCount: number;

  /**
   * The number of converted clicks.
   */
  conversionCount: number;

  /**
   * A list of conversion events with their date.
   */
  dates: ConversionRateEvent[];
};
