// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { NoResultsRateEvent } from './noResultsRateEvent';

export type GetNoResultsRateResponse = {
  /**
   * [Click-through rate (CTR)](https://www.algolia.com/doc/guides/search-analytics/concepts/metrics/#click-through-rate).
   */
  rate: number;

  /**
   * Number of occurrences.
   */
  count: number;

  /**
   * Number of occurrences.
   */
  noResultCount: number;

  /**
   * Overall count of searches without results plus a daily breakdown.
   */
  dates: NoResultsRateEvent[];
};
