// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { DailyPurchaseRates } from './dailyPurchaseRates';

export type GetPurchaseRateResponse = {
  /**
   * Purchase rate, calculated as number of tracked searches with at least one purchase event divided by the number of tracked searches. If null, Algolia didn\'t receive any search requests with `clickAnalytics` set to true.
   */
  rate: number | null;

  /**
   * Number of tracked searches. Tracked searches are search requests where the `clickAnalytics` parameter is true.
   */
  trackedSearchCount: number;

  /**
   * Number of purchase events from this search.
   */
  purchaseCount: number;

  /**
   * Daily purchase rates.
   */
  dates: DailyPurchaseRates[];
};
