// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { SearchNoResultEvent } from './searchNoResultEvent';

export type GetSearchesNoResultsResponse = {
  /**
   * Searches with no results.
   */
  searches: SearchNoResultEvent[];
};
