// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { DailySearchesNoClicks } from './dailySearchesNoClicks';

export type GetSearchesNoClicksResponse = {
  /**
   * Searches without any clicks.
   */
  searches: DailySearchesNoClicks[];
};
