// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { GetTopFilterForAttribute } from './getTopFilterForAttribute';

export type GetTopFilterForAttributeResponse = {
  /**
   * Filter values for an attribute.
   */
  values: GetTopFilterForAttribute[];
};
