// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { GetTopFilterAttribute } from './getTopFilterAttribute';

export type GetTopFilterAttributesResponse = {
  /**
   * A list of attributes with their count.
   */
  attributes: GetTopFilterAttribute[];
};
