// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { DailyUsers } from './dailyUsers';

export type GetUsersCountResponse = {
  /**
   * Number of unique users.
   */
  count: number;

  /**
   * Daily number of unique users.
   */
  dates: DailyUsers[];
};
