// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type ParameterReference = {
  /**
   * Domain the parameter belongs to.
   */
  domain?: string | undefined;

  /**
   * Parameter identifier that resolves to a value supplied in `parameters`.
   */
  kind: string;
};
