// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { FieldReference } from './fieldReference';
import type { FilterDefinition } from './filterDefinition';
import type { OrderDefinition } from './orderDefinition';
import type { ParameterDefinition } from './parameterDefinition';

/**
 * When `groupBy` is set, `orderBy` is required.
 */
export type TablePayload = {
  /**
   * Default domain propagated to entries that omit their own.
   */
  domain?: string | undefined;

  /**
   * Fields to aggregate.
   */
  metrics: Array<FieldReference>;

  /**
   * Fields to split rows by.
   */
  groupBy?: Array<FieldReference> | undefined;

  /**
   * Filter conditions.
   */
  filters?: Array<FilterDefinition> | undefined;

  /**
   * Literal values referenced by the query.
   */
  parameters: Array<ParameterDefinition>;

  /**
   * Sort specification. Required when `groupBy` is set.
   */
  orderBy?: Array<OrderDefinition> | undefined;

  /**
   * Maximum number of rows to return.
   */
  limit?: number | undefined;

  /**
   * Number of rows to skip.
   */
  offset?: number | undefined;
};
