// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type TableResponse = {
  /**
   * Result rows. Each row is a flat object of the requested fields.
   */
  rows: Array<{ [key: string]: any }>;
};
