// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { FieldReference } from './fieldReference';
import type { FilterDefinition } from './filterDefinition';
import type { ParameterDefinition } from './parameterDefinition';

export type TimeseriesPayload = {
  /**
   * Default domain propagated to entries that omit their own.
   */
  domain?: string | undefined;

  /**
   * Fields to aggregate.
   */
  metrics: Array<FieldReference>;

  /**
   * Fields to split the series by.
   */
  groupBy?: Array<FieldReference> | undefined;

  /**
   * Filter conditions.
   */
  filters?: Array<FilterDefinition> | undefined;

  /**
   * Literal values referenced by the query.
   */
  parameters: Array<ParameterDefinition>;

  /**
   * Maximum number of series (groupBy values) to return.
   */
  limit?: number | undefined;

  /**
   * Number of series to skip.
   */
  offset?: number | undefined;
};
