// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { TopHit } from './topHit';

export type TopHitsResponse = {
  /**
   * A list of top hits with their count.
   */
  hits: TopHit[];
};
