// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { TopHitWithAnalytics } from './topHitWithAnalytics';

export type TopHitsResponseWithAnalytics = {
  /**
   * A list of top hits with their count and analytics.
   */
  hits: TopHitWithAnalytics[];
};
