// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { TopHitWithRevenueAnalytics } from './topHitWithRevenueAnalytics';

export type TopHitsResponseWithRevenueAnalytics = {
  /**
   * Most frequent search results with click, conversion, and revenue metrics.
   */
  hits: TopHitWithRevenueAnalytics[];
};
