// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { TopSearchWithAnalytics } from './topSearchWithAnalytics';

export type TopSearchesResponseWithAnalytics = {
  /**
   * Top searches with their hits count and analytics.
   */
  searches: TopSearchWithAnalytics[];
};
