const clientMethods = [
  'addApiKey',
  'batch',
  'clearCache',
  'copyIndex',
  'deleteApiKey',
  'deleteIndex',
  'getApiKey',
  'getLogs',
  'getTimeouts',
  'initIndex',
  'listApiKeys',
  'listIndexes',
  'moveIndex',
  'search',
  'sendQueriesBatch',
  'setExtraHeader',
  'setRequestTimeout',
  'setSecurityTags',
  'setTimeouts',
  'updateApiKey',
];

const nodeOnlyClientMethods = [
  'destroy',
  'disableRateLimitForward',
  'disableSecuredAPIKey',
  'enableRateLimitForward',
  'generateSecuredApiKey',
  'useSecuredAPIKey',
];
