// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Properties for the `computeRealtimeUser` method.
 */
export type ComputeRealtimeUserProps = {
  /**
   * Unique identifier representing a user for which to fetch the personalization profile.
   */
  userToken: string;
};

/**
 * Properties for the `customDelete` method.
 */
export type CustomDeleteProps = {
  /**
   * Path of the endpoint, anything after \"/1\" must be specified.
   */
  path: string;
  /**
   * Query parameters to apply to the current query.
   */
  parameters?: { [key: string]: any } | undefined;
};

/**
 * Properties for the `customGet` method.
 */
export type CustomGetProps = {
  /**
   * Path of the endpoint, anything after \"/1\" must be specified.
   */
  path: string;
  /**
   * Query parameters to apply to the current query.
   */
  parameters?: { [key: string]: any } | undefined;
};

/**
 * Properties for the `customPost` method.
 */
export type CustomPostProps = {
  /**
   * Path of the endpoint, anything after \"/1\" must be specified.
   */
  path: string;
  /**
   * Query parameters to apply to the current query.
   */
  parameters?: { [key: string]: any } | undefined;
  /**
   * Parameters to send with the custom request.
   */
  body?: Record<string, unknown> | undefined;
};

/**
 * Properties for the `customPut` method.
 */
export type CustomPutProps = {
  /**
   * Path of the endpoint, anything after \"/1\" must be specified.
   */
  path: string;
  /**
   * Query parameters to apply to the current query.
   */
  parameters?: { [key: string]: any } | undefined;
  /**
   * Parameters to send with the custom request.
   */
  body?: Record<string, unknown> | undefined;
};

/**
 * Properties for the `deleteUser` method.
 */
export type DeleteUserProps = {
  /**
   * ID of the user.
   */
  userID: string;
};

/**
 * Properties for the `getRealtimeUser` method.
 */
export type GetRealtimeUserProps = {
  /**
   * Unique identifier representing a user for which to fetch the personalization profile.
   */
  userToken: string;
};

/**
 * Properties for the `getUser` method.
 */
export type GetUserProps = {
  /**
   * ID of the user.
   */
  userID: string;
};

/**
 * Properties for the `getUsers` method.
 */
export type GetUsersProps = {
  /**
   * Filter users by start date (in RFC3339 format). Only users that were updated after the passed date will be returned.
   */
  startDate?: string | undefined;
  /**
   * Filter users by end date (in RFC3339 format). Only users that were updated before the passed date will be returned.
   */
  endDate?: string | undefined;
  /**
   * Filter users by matching indices. If multiple indices are passed, returned users will match all indices.
   */
  indices?: Array<string> | undefined;
  /**
   * Filter users by affinity name and value. If multiple values are passed, returned users will match all values.
   */
  affinity?: Array<string> | undefined;
  /**
   * Limit the number of users in the response. The value of this parameter ranges from 1 to 1000.
   */
  limit?: number | undefined;
  /**
   * Reference for the next page, when navigating forward using pagination. Can\'t be used in the same request as `previousPageToken`.
   */
  nextPageToken?: string | undefined;
  /**
   * Reference for the previous page, when navigating backward using pagination. Can\'t be used in the same request as `nextPageToken`.
   */
  previousPageToken?: string | undefined;
};
