// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { GenericNotFound } from './genericNotFound';
import type { NotFound } from './notFound';

export type ErrorResponsesGenericNotFound = {
  status?: NotFound | undefined;

  message?: GenericNotFound | undefined;
};
