// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Details about the response, such as error messages.
 */
export type FeatureNotEnabled =
  | 'Predictive profiles are not allowed for this app. Please contact support to upgrade your plan: https://support.algolia.com/'
  | 'Realtime Personalization is not allowed for this app. Please contact support to upgrade your plan: https://support.algolia.com/';
