// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * url for a search banner image.
 */
export type BannerImageUrl = {
  url?: string;
};
