// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type FacetStats = {
  /**
   * Minimum value in the results.
   */
  min?: number | undefined;

  /**
   * Maximum value in the results.
   */
  max?: number | undefined;

  /**
   * Average facet value in the results.
   */
  avg?: number | undefined;

  /**
   * Sum of all values in the results.
   */
  sum?: number | undefined;
};
