// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * An object that contains the extra key-value pairs provided in the injectedItem definition.
 */
export type HitMetadata = Record<string, any> & {
  /**
   * The key of the injectedItem that inserted this metadata.
   */
  _injectedItemKey?: string | undefined;
};
