// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { CompositionInset } from './compositionInset';
import type { Main } from './main';

export type Injection = {
  main: Main;

  /**
   * list of insets of the current Composition.
   */
  insets?: Array<CompositionInset>;
};
