// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { InjectedItemMetadata } from './injectedItemMetadata';
import type { InjectedItemSource } from './injectedItemSource';

export type InjectedItem = {
  /**
   * injected Item unique identifier.
   */
  key: string;

  source: InjectedItemSource;

  position: number;

  length: number;

  metadata?: InjectedItemMetadata | undefined;
};
