// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { SearchHits } from './searchHits';
import type { SearchPagination } from './searchPagination';

export type SearchResultsItem<T = Record<string, unknown>> = SearchHits<T> & SearchPagination;
