// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { RequestBody } from '../model/requestBody';
import type { SearchForFacetValuesRequest } from '../model/searchForFacetValuesRequest';

/**
 * Properties for the `search` method.
 */
export type SearchProps = {
  /**
   * Unique Composition ObjectID.
   */
  compositionID: string;
  requestBody: RequestBody;
};

/**
 * Properties for the `searchForFacetValues` method.
 */
export type SearchForFacetValuesProps = {
  /**
   * Unique Composition ObjectID.
   */
  compositionID: string;
  /**
   * Facet attribute in which to search for values.  This attribute must be included in the `attributesForFaceting` index setting with the `searchable()` modifier.
   */
  facetName: string;
  searchForFacetValuesRequest?: SearchForFacetValuesRequest;
};
