// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { CompositionRunAppliedRules } from './compositionRunAppliedRules';

export type CompositionRunSearchResponse = Record<string, any> & {
  /**
   * The objectID of the composition which generated this result set.
   */
  objectID: string;

  appliedRules?: Array<CompositionRunAppliedRules> | undefined;
};
