// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * An object that contains the extra key-value pairs provided in the injectedItem definition. Only present on hits inserted by an injectedItem that defines metadata, either in its `metadata` field or sent by an external source.
 */
export type HitMetadata = Record<string, any> & {
  /**
   * The key of the injectedItem that inserted this metadata. Only present when the injectedItem\'s `metadata.hits.addItemKey` is `true`.
   */
  _injectedItemKey?: string | undefined;
};
