// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { InjectionMainRecommend } from './injectionMainRecommend';

/**
 * Organic result set will originate from a recommend request.
 */
export type InjectionMainRecommendSource = {
  recommend: InjectionMainRecommend;
};
