// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Recommendation model to use for retrieving recommendations.
 */
export type Model = 'trending-items';
