// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Agent Studio Result Card to display for a given search.
 */
export type ResultCard = {
  /**
   * Whether to show the Result Card for the current search.
   */
  enabled?: boolean | undefined;
};
