// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ResultsInjectedItemAppliedRulesInfoResponse } from './resultsInjectedItemAppliedRulesInfoResponse';

export type ResultsInjectedItemInfoResponse = Record<string, any> & {
  /**
   * The key of the injected group.
   */
  key: string;

  appliedRules?: Array<ResultsInjectedItemAppliedRulesInfoResponse> | undefined;
};
