// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type ResultsInjectedItemAppliedRulesInfoResponse = {
  /**
   * The objectID of the applied index level rule on this injected group.
   */
  objectID: string;
};
