// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { FacetHits } from './facetHits';

export type SearchForFacetValuesResults = {
  indexName: string;

  /**
   * Matching facet values.
   */
  facetHits: Array<FacetHits>;

  /**
   * Whether the facet count is exhaustive (true) or approximate (false). For more information, see [Why are my facet and hit counts not accurate](https://support.algolia.com/hc/articles/4406975248145-Why-are-my-facet-and-hit-counts-not-accurate).
   */
  exhaustiveFacetsCount: boolean;

  /**
   * Time the server took to process the request, in milliseconds.
   */
  processingTimeMS?: number | undefined;
};
