#!/usr/bin/env bash

set -e # exit when error

if [ -x "$(command -v brew)" ] && [ -x "$(brew --prefix nvm)" ]; then
  source $(brew --prefix nvm)/nvm.sh
else
  source ~/.nvm/nvm.sh
fi

# our unit tests are currently failing on v7+ because of faux-jax
nvm install 7
node test/run-node.js | tap-bail | tap-dot
