#!/usr/bin/env bash

set -e # exit when error

[ -z $TRAVIS_BUILD_NUMBER ] && CI='false' || CI='true'

if [ $CI == 'true' ]; then
  set -x # debug messages
fi

[ -z $TRAVIS_PULL_REQUEST ] && TRAVIS_PULL_REQUEST='false'

echo "Browser test"

echo "Browser test: build"
APP_ENV=production npm run build

echo "Browser test: integration"
DEBUG=zuul* zuul --no-coverage -- test/run-integration.js

if [ $TRAVIS_PULL_REQUEST != 'false' ]; then
  echo "No browser unit test for PR"
else
  echo "Browser test: unit"
  DEBUG=zuul* zuul --no-coverage -- test/run-browser.js
fi
