#!/usr/bin/env bash

set -e # exit when error

[ -z $TRAVIS_BUILD_NUMBER ] && CI='false' || CI='true'

echo "Test"

echo "Test: node"
./scripts/test-node

#####
# TODO: remove before merging the PR
echo "Test: ci"
./scripts/test-ci
#####

echo "Test: lint"
./scripts/lint
