#!/usr/bin/env bash

set -e # exit when error

[ -z $TRAVIS_BUILD_NUMBER ] && CI='false' || CI='true'

echo "Test"

echo "Test: node"
./scripts/test-node

echo "Test: phantom"
./scripts/test-phantom

echo "Test: lint"
./scripts/lint
