#!/usr/bin/env bash

source ~/.nvm/nvm.sh

set -e # exit when error
set -x # debug messages

[ -z $TRAVIS_PULL_REQUEST ] && TRAVIS_PULL_REQUEST='false'
[ -z $TRAVIS_BUILD_NUMBER ] && TRAVIS_BUILD_NUMBER='false'

echo "Node test 0.12"

# always test on node 0.12
echo "Node test 0.12: unit"
nvm use 0.12
node test/run-node.js

# in local env, no integration test
[ $TRAVIS_BUILD_NUMBER != 'false' ] && echo "Node test 0.12: integration" && node test/run-integration.js

# in a PR or in local environement, test only on node 0.12
if [ $TRAVIS_PULL_REQUEST != 'false' ] || [ $TRAVIS_BUILD_NUMBER == 'false' ]; then
  echo 'Skipping 0.10 and iojs tests (PR or local)'
  exit 0
else
  echo "Node test 0.10"

  nvm use 0.10
  echo "Node test 0.10: unit"
  node test/run-node.js

  echo "Node test 0.10: integration"
  node test/run-integration.js

  echo "Node test iojs"
  nvm use iojs

  echo "Node test iojs: unit"
  node test/run-node.js

  echo "Node test iojs: integration"
  node test/run-integration.js
fi

# switch back to node.js 0.12
nvm use 0.12
