#!/usr/bin/env bash

set -e # exit when error

echo "CI test"

echo "CI test: node"
./scripts/test-node

echo "CI test: browser"
./scripts/test-browser

echo "CI test: lint"
./scripts/lint

echo "Testing bundle size"
bundlesize
