#!/usr/bin/env bash

if [ -x "$(command -v brew)" ] && [ -x "$(brew --prefix nvm)" ]; then
  source $(brew --prefix nvm)/nvm.sh
else
  source ~/.nvm/nvm.sh
fi

set -e # exit when error

echo "Node test stable: integration"
node test/run-integration.js

echo "Node test 0.10: integration"
nvm install 0.10
node test/run-integration.js | tap-bail | tap-dot

echo "Node test 0.12: integration"
nvm install 0.12
node test/run-integration.js | tap-bail | tap-dot

echo "Node test 4: integration"
nvm install 4
node test/run-integration.js | tap-bail | tap-dot

echo "Node test 5: integration"
nvm install 5
node test/run-integration.js | tap-bail | tap-dot

echo "Node test 6: integration"
nvm install 6
node test/run-integration.js | tap-bail | tap-dot

echo "Node test 8: integration"
nvm install 8
node test/run-integration.js | tap-bail | tap-dot

echo "Node test 10: integration"
nvm install 10
node test/run-integration.js | tap-bail | tap-dot
