#!/usr/bin/env bash

set -e # exit when error

[ -z $TRAVIS_BUILD_NUMBER ] && CI='false' || CI='true'

[ -z $TRAVIS_PULL_REQUEST ] && TRAVIS_PULL_REQUEST='false'

if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [[ ! "$TRAVIS_PULL_REQUEST_SLUG" =~ ^algolia\/ ]]; then
  eval $(./algolia-keys export);
  TEST_SUITE='community'
fi

echo "CI test"

echo "CI test: node"
./scripts/test-node

echo "CI test: browser"
./scripts/test-browser

if [ $TRAVIS_PULL_REQUEST != 'false' ]; then
  echo 'No parse-cloud test for pull requests'
else
  echo "CI test: parse-cloud"
  ./scripts/test-parse-cloud
fi

echo "CI test: lint"
./scripts/lint

echo "Testing bundle size"
bundlesize
