#!/usr/bin/env bash

set -e # exit when error

[ -z $TRAVIS_BUILD_NUMBER ] && CI='false' || CI='true'

echo "Phantom test"

if [ $CI == 'false' ]; then
  zuul --no-coverage --phantom -- test/run-browser.js
else
  DEBUG=zuul* zuul --no-coverage --phantom -- test/run-browser.js
fi
