// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Authentication input for OAuth login.
 */
export type AuthOAuth = {
  /**
   * The OAuth endpoint URL.
   */
  url: string;

  /**
   * The clientID.
   */
  client_id: string;

  /**
   * The secret.
   */
  client_secret: string;
};
