// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Type of the Authentication, defines what kind of object is stored in the input.
 */
export type AuthenticationType =
  | 'algolia'
  | 'apiKey'
  | 'basic'
  | 'googleServiceAccount'
  | 'oauth';
