// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Credentials for authenticating with an API key.
 */
export type AuthAPIKeyPartial = {
  /**
   * API key. This field is `null` in the API response.
   */
  key?: string | undefined;
};
