// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Custom fields from commercetools to add to the records.  For more information, see [Using Custom Types and Custom Fields](https://docs.commercetools.com/tutorials/custom-types).
 */
export type CommercetoolsCustomFields = {
  /**
   * Inventory custom fields.
   */
  inventory?: string[] | null;

  /**
   * Price custom fields.
   */
  price?: string[] | null;

  /**
   * Category custom fields.
   */
  category?: string[] | null;
};
