// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Used to sort the Destination list endpoint.
 */
export type DestinationSortKeys = 'createdAt' | 'name' | 'type' | 'updatedAt';
