// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * The registry where the image is stored.
 */
export type DockerRegistry = 'dockerhub' | 'gcr';
