// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * HTTP method to be used for retrieving your data.
 */
export type MethodType = 'GET' | 'POST';
