// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Authentication resource not tied to any ecommerce platform, used for filtering.
 */
export type PlatformNone = 'none';
