// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * A code for the task run\'s outcome. A readable description of the code is included in the `reason` response property.
 */
export type RunReasonCode =
  | 'internal'
  | 'cancelled'
  | 'critical'
  | 'no_events'
  | 'too_many_errors'
  | 'lacking_events'
  | 'ok'
  | 'blocking'
  | 'idle';
