// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * An identifier that pairs with the outcome reason.
 */
export type RunReasonCode =
  | 'critical'
  | 'discarded'
  | 'internal'
  | 'no_events'
  | 'ok'
  | 'too_many_errors';
