// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Represents a metafield in Shopify.
 */
export type ShopifyMetafield = {
  namespace: string;

  key: string;

  value: string;
};
