// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Specific configuration attributes of a `shopify` source.
 */
export type SourceUpdateShopify = {
  /**
   * Feature flags for the Shopify source.
   */
  featureFlags?: { [key: string]: any } | undefined;
};
