// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Specific configuration attributes of a `ga4BigqueryExport` source.
 */
export type SourceGA4BigQueryExport = {
  /**
   * GCP project ID that the BigQuery export writes to.
   */
  projectID: string;

  /**
   * BigQuery dataset ID that the BigQuery export writes to.
   */
  datasetID: string;

  /**
   * Prefix of the tables that the BigQuery Export writes to.
   */
  tablePrefix: string;
};
