// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { SourceBigQuery } from './sourceBigQuery';
import type { SourceCSV } from './sourceCSV';
import type { SourceJSON } from './sourceJSON';
import type { SourceUpdateCommercetools } from './sourceUpdateCommercetools';
import type { SourceUpdateDocker } from './sourceUpdateDocker';

export type SourceUpdateInput =
  | SourceBigQuery
  | SourceCSV
  | SourceJSON
  | SourceUpdateCommercetools
  | SourceUpdateDocker;
