// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { SourceBigCommerce } from './sourceBigCommerce';
import type { SourceCSV } from './sourceCSV';
import type { SourceCommercetools } from './sourceCommercetools';
import type { SourceJSON } from './sourceJSON';

export type SourceInput =
  | SourceBigCommerce
  | SourceCommercetools
  | SourceCSV
  | SourceJSON;
