// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { SourceUpdateInput } from './sourceUpdateInput';

export type SourceUpdate = {
  /**
   * Descriptive name of the source.
   */
  name?: string | undefined;

  input?: SourceUpdateInput | undefined;

  /**
   * Universally unique identifier (UUID) of an authentication resource.
   */
  authenticationID?: string | undefined;
};
