// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { StreamingTriggerType } from './streamingTriggerType';

/**
 * Trigger input for continuously running tasks.
 */
export type StreamingTrigger = {
  type: StreamingTriggerType;
};
