// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ActionType } from './actionType';
import type { Notifications } from './notifications';
import type { Policies } from './policies';
import type { TaskInput } from './taskInput';

/**
 * API request body for updating a task.
 */
export type TaskReplace = {
  /**
   * Universally unique identifier (UUID) of a destination resource.
   */
  destinationID: string;

  action: ActionType;

  subscriptionAction?: ActionType | undefined;

  /**
   * Cron expression for the task\'s schedule.
   */
  cron?: string | undefined;

  /**
   * Whether the task is enabled.
   */
  enabled?: boolean | undefined;

  /**
   * Maximum accepted percentage of failures for a task run to finish successfully.
   */
  failureThreshold?: number | undefined;

  input?: TaskInput | undefined;

  /**
   * Date and time when the last cursor was created, in RFC 3339 format.
   */
  cursor?: string | undefined;

  notifications?: Notifications | undefined;

  policies?: Policies | undefined;
};
