// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * The response from the API after a task creation.
 */
export type TaskCreateResponse = {
  /**
   * The task UUID.
   */
  taskID: string;

  /**
   * Date of creation (RFC3339 format).
   */
  createdAt: string;
};
