// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * API response for creating a task.
 */
export type TaskCreateResponse = {
  /**
   * Universally unique identifier (UUID) of a task.
   */
  taskID: string;

  /**
   * Date of creation in RFC 3339 format.
   */
  createdAt: string;
};
