// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Input for a transformation that contains the source code of the transformation.
 */
export type TransformationCode = {
  /**
   * The source code of the transformation.
   */
  code: string;
};
