// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Property by which to sort the list of transformations.
 */
export type TransformationSortKeys = 'name' | 'updatedAt' | 'createdAt';
