// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type FacetHits = {
  /**
   * Facet value.
   */
  value: string;

  /**
   * Markup text with `facetQuery` matches highlighted.
   */
  highlighted: string;

  /**
   * Number of records containing this facet value. This takes into account the extra search parameters specified in the query. Like for a regular search query, the [counts may not be exhaustive](https://support.algolia.com/hc/en-us/articles/4406975248145-Why-are-my-facet-and-hit-counts-not-accurate-).
   */
  count: number;
};
