// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { FbtModel } from './fbtModel';

export type FrequentlyBoughtTogether = {
  model: FbtModel;

  /**
   * Unique record identifier.
   */
  objectID: string;
};
