// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Type of operation to perform (move or copy).
 */
export type OperationType = 'copy' | 'move';
