// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { FallbackParams } from './fallbackParams';
import type { RecommendedForYouModel } from './recommendedForYouModel';

export type RecommendedForYou = {
  model: RecommendedForYouModel;

  fallbackParameters?: FallbackParams;
};
