// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Selects a strategy to remove words from the query when it doesn\'t match any hits.
 */
export type RemoveWordsIfNoResults =
  | 'allOptional'
  | 'firstWords'
  | 'lastWords'
  | 'none';
