// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Map of language ISO code supported by the dictionary (e.g., \"en\" for English) to a boolean value.
 */
export type StandardEntries = {
  /**
   * Language ISO code.
   */
  plurals?: Record<string, boolean> | null;

  /**
   * Language ISO code.
   */
  stopwords?: Record<string, boolean> | null;

  /**
   * Language ISO code.
   */
  compounds?: Record<string, boolean> | null;
};
