// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Unique user ID.
 */
export type UserId = {
  /**
   * UserID of the user.
   */
  userID: string;

  /**
   * Cluster to which the user is assigned.
   */
  clusterName: string;

  /**
   * Number of records belonging to the user.
   */
  nbRecords: number;

  /**
   * Data size used by the user.
   */
  dataSize: number;
};
