export type IndexSettings = {
  readonly searchableAttributes?: readonly string[];
  readonly attributesForFaceting?: readonly string[];
  readonly unretrievableAttributes?: readonly string[];
  readonly attributesToRetrieve?: readonly string[];
  readonly ranking?: readonly string[];
  readonly customRanking?: readonly string[];
  readonly replicas?: readonly string[];
  readonly primary?: string;
  readonly maxValuesPerFacet?: number | null;
  readonly sortFacetValuesBy?: string;
  readonly attributesToHighlight?: readonly string[];
  readonly attributesToSnippet?: readonly string[];
  readonly highlightPreTag?: string;
  readonly highlightPostTag?: string;
  readonly snippetEllipsisText?: string;
  readonly restrictHighlightAndSnippetArrays?: boolean | null;
  readonly hitsPerPage?: number | null;
  readonly paginationLimitedTo?: number | null;
  readonly minWordSizefor1Typo?: number | null;
  readonly minWordSizefor2Typos?: number | null;
  readonly typoTolerance?: string | boolean;
  readonly allowTyposOnNumericTokens?: boolean | null;
  readonly disableTypoToleranceOnAttributes?: readonly string[];
  readonly disableTypoToleranceOnWords?: readonly string[];
  readonly separatorsToIndex?: string;
  readonly ignorePlurals?: readonly string[] | boolean;
  readonly queryLanguages?: readonly string[];
  readonly enableRules?: boolean | null;
  readonly queryType?: string;
  readonly removeWordsIfNoResults?: string;
  readonly advancedSyntax?: boolean | null;
  readonly advancedSyntaxFeatures?: readonly string[];
  readonly optionalWords?: readonly string[];
  readonly disablePrefixOnAttributes?: readonly string[];
  readonly disableExactOnAttributes?: readonly string[];
  readonly exactOnSingleWordQuery?: string;
  readonly alternativesAsExact?: readonly string[];
  readonly removeStopWords?: readonly string[] | boolean;
  readonly numericAttributesForFiltering?: readonly string[];
  readonly allowCompressionOfIntegerArray?: boolean | null;
  readonly attributeForDistinct?: string;
  readonly distinct?: number | boolean;
  readonly replaceSynonymsInHighlight?: boolean | null;
  readonly attributeCriteriaComputedByMinProximity?: boolean | null;
  readonly minProximity?: number | null;
  readonly responseFields?: readonly string[];
  readonly maxFacetHits?: number | null;
  readonly camelCaseAttributes?: readonly string[];
  readonly decompoundedAttributes?: { readonly [key: string]: readonly string[] };
  readonly keepDiacriticsOnCharacters?: string;
  readonly userData?: any;
};
