// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { Variant } from './variant';

export type ABTest = {
  /**
   * Unique A/B test ID.
   */
  abTestID: number;

  /**
   * [A/B test significance](https://www.algolia.com/doc/guides/ab-testing/what-is-ab-testing/in-depth/how-ab-test-scores-are-calculated/#statistical-significance-or-chance) based on click data. A value of 0.95 or over is considered to be _significant_.
   */
  clickSignificance: number;

  /**
   * [A/B test significance](https://www.algolia.com/doc/guides/ab-testing/what-is-ab-testing/in-depth/how-ab-test-scores-are-calculated/#statistical-significance-or-chance) based on conversion. A value of 0.95 or over is considered to be _significant_.
   */
  conversionSignificance: number;

  /**
   * [A/B test significance](https://www.algolia.com/doc/guides/ab-testing/what-is-ab-testing/in-depth/how-ab-test-scores-are-calculated/#statistical-significance-or-chance) based on add-to-cart data. A value of 0.95 or over is considered to be _significant_.
   */
  addToCartSignificance: number;

  /**
   * [A/B test significance](https://www.algolia.com/doc/guides/ab-testing/what-is-ab-testing/in-depth/how-ab-test-scores-are-calculated/#statistical-significance-or-chance) based on purchase data. A value of 0.95 or over is considered to be _significant_.
   */
  purchaseSignificance: number;

  /**
   * [A/B test significance](https://www.algolia.com/doc/guides/ab-testing/what-is-ab-testing/in-depth/how-ab-test-scores-are-calculated/#statistical-significance-or-chance) based on revenue data. A value of 0.95 or over is considered to be _significant_.
   */
  revenueSignificance: Record<string, number>;

  /**
   * Update date timestamp in [ISO-8601](https://wikipedia.org/wiki/ISO_8601) format.
   */
  updatedAt: string;

  /**
   * Creation date timestamp in [ISO-8601](https://wikipedia.org/wiki/ISO_8601) format.
   */
  createdAt: string;

  /**
   * End date timestamp in [ISO-8601](https://wikipedia.org/wiki/ISO_8601) format.
   */
  endAt: string;

  /**
   * A/B test name.
   */
  name: string;

  /**
   * A/B test status.
   */
  status: string;

  /**
   * A/B test variants.
   */
  variants: Variant[];
};
