// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type AbTestsVariant = {
  /**
   * A/B test index.
   */
  index: string;

  /**
   * A/B test traffic percentage.
   */
  trafficPercentage: number;

  /**
   * A/B test description.
   */
  description?: string;
};
