// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Empty searches removed from the A/B test as a result of configuration settings.
 */
export type EmptySearchFilter = {
  /**
   * Number of users removed from the A/B test.
   */
  usersCount?: number;

  /**
   * Number of tracked searches removed from the A/B test.
   */
  trackedSearchesCount?: number;
};
