// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { EmptySearch } from './emptySearch';
import type { FeatureFilters } from './featureFilters';
import type { MinimumDetectableEffect } from './minimumDetectableEffect';
import type { Outliers } from './outliers';

/**
 * A/B test configuration for estimating the sample size and duration using minimum detectable effect.
 */
export type EstimateConfiguration = {
  featureFilters?: FeatureFilters | undefined;

  outliers?: Outliers | undefined;

  emptySearch?: EmptySearch | undefined;

  minimumDetectableEffect: MinimumDetectableEffect;
};
