// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { AgentCompletionAlgoliaParams } from './agentCompletionAlgoliaParams';
import type { AgentTestConfiguration } from './agentTestConfiguration';
import type { MessagesUnion } from './messagesUnion';

/**
 * Request model for creating a completion for an assistant.
 */
export type AgentCompletionRequest = {
  configuration?: AgentTestConfiguration | undefined;

  messages?: MessagesUnion | null | undefined;

  /**
   * Optional conversation id.
   */
  id?: string | undefined;

  algolia?: AgentCompletionAlgoliaParams | undefined;

  /**
   * Approval decisions for pending tool calls keyed by toolCallId.
   */
  toolApprovals?: Record<string, unknown> | undefined;
};
