// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Configuration for the algolia_display_results tool.
 */
export type AlgoliaDisplayResultsToolConfig = {
  name?: string | undefined;

  type: string;

  minGroups?: number | undefined;

  maxGroups?: number | undefined;

  minResultsPerGroup?: number | undefined;

  maxResultsPerGroup?: number | undefined;
};
