// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { IndexSearchParameters } from './indexSearchParameters';
import type { SearchParameters } from './searchParameters';

export type AlgoliaSearchToolIndexConfig = {
  index: string;

  description: string;

  enhancedDescription?: string | undefined;

  searchParameters?: SearchParameters | null | undefined;

  searchControls?: IndexSearchParameters | null | undefined;
};
