// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Request body to add a single allowed domain.
 */
export type AllowedDomainCreate = {
  /**
   * Domain or pattern, e.g. https://app.example.com or *.example.com.
   */
  domain: string;
};
