// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { AllowedDomainResponse } from './allowedDomainResponse';

/**
 * List of allowed domains for an application.
 */
export type AllowedDomainListResponse = {
  domains: Array<AllowedDomainResponse>;
};
