// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { AssistantPartV5 } from './assistantPartV5';

export type AssistantMessageV5 = {
  id?: string | undefined;

  role: string;

  parts?: Array<AssistantPartV5> | undefined;
};
