// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Support Compatibility modes for the completion API.
 */
export type CompatibilityMode = 'ai-sdk-4' | 'ai-sdk-5';
