// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { ConversationMetadata } from './conversationMetadata';
import type { FeedbackResponse } from './feedbackResponse';

/**
 * Lightweight response model without its messages.
 */
export type ConversationBaseResponse = {
  id: string;

  agentId: string;

  title?: string | null | undefined;

  createdAt: string;

  updatedAt: string;

  lastActivityAt?: string | null | undefined;

  userToken?: string | null | undefined;

  isFromDashboard?: boolean | undefined;

  messageCount?: number | undefined;

  totalInputTokens?: number | undefined;

  totalOutputTokens?: number | undefined;

  totalTokens?: number | undefined;

  conversationMetadata?: ConversationMetadata | null | undefined;

  feedback?: Array<FeedbackResponse> | null | undefined;
};
