// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { VoteEnum } from './voteEnum';

/**
 * Request model for updating an existing feedback entry.
 */
export type FeedbackUpdateRequest = {
  messageId: string;

  agentId: string;

  vote?: VoteEnum | null | undefined;

  tags?: Array<string> | null | undefined;

  notes?: string | null | undefined;
};
