// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { OneOfEnum } from './oneOfEnum';

/**
 * Minimal record of a guardrail decision, persisted on a blocked assistant message.  Present only when a guardrail blocks a turn (the persisted parts are then just the fallback text); ``null`` on ordinary messages. Lets a blocked turn be told apart from a short reply using conversation data alone.
 */
export type GuardrailOutcome = {
  blocked: boolean;

  category: string;

  guardrailType?: OneOfEnum | null | undefined;
};
