// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { Episode } from './episode';
import type { MemoryType } from './memoryType';

/**
 * A stored memory record.
 */
export type MemoryRecord = {
  memoryType?: MemoryType | undefined;

  episode?: Episode | null | undefined;

  /**
   * Self-contained, first-person memory for long-term recall.
   */
  text: string;

  /**
   * Verbatim conversation extract, not paraphrased.
   */
  rawExtract: string;

  /**
   * Keywords for retrieval: entities, context, search terms.
   */
  keywords?: Array<string> | undefined;

  /**
   * Topics that classify the memory. Each must be one of: [complaints, entertainment, family, feedback, finance, food, goals, health, history, hobbies, learning, praise, preferences, schedule, shopping, technical, travel, work].
   */
  topics?: Array<string> | undefined;

  /**
   * Arbitrary labels/themes for flexible categorization (e.g., \'Q1-goals\', \'paris-trip\', \'vip-customer\').
   */
  _tags?: Array<string> | undefined;

  /**
   * Phrases that cause the API to recall this memory.
   */
  recallTriggers?: Array<string> | undefined;

  /**
   * ObjectID of existing memory to update. Leave empty for new memory.
   */
  objectID?: string | null | undefined;

  /**
   * Application ID.
   */
  appId?: string | undefined;

  /**
   * Agent IDs with access: [\'agent1\'], [\'*\'] for all, [\'*\', \'-agent1\'] to exclude.
   */
  agentIDs?: Array<string> | undefined;

  /**
   * User ID.
   */
  userID?: string | undefined;

  /**
   * Epoch seconds.
   */
  createdAt?: number | undefined;

  /**
   * Epoch seconds.
   */
  updatedAt?: number | undefined;
};
