// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { MessagePart } from './messagePart';
import type { MessageRole } from './messageRole';

/**
 * Response model for a message.
 */
export type MessageResponse = {
  id: string;

  conversationId: string;

  role: MessageRole;

  parts: Array<MessagePart>;

  createdAt: string;

  updatedAt: string;

  model?: string | null | undefined;

  inputTokens?: number | null | undefined;

  outputTokens?: number | null | undefined;

  turnContext?: { [key: string]: string } | null | undefined;
};
