// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { AgentWithVersionResponse } from './agentWithVersionResponse';
import type { PaginationMetadata } from './paginationMetadata';

export type PaginatedAgentsResponse = {
  data: Array<AgentWithVersionResponse>;

  pagination: PaginationMetadata;
};
