// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { InputUnion } from './inputUnion';

export type ProviderAuthenticationResponse = {
  id: string;

  name: string;

  providerName: string;

  input: InputUnion;

  createdAt: string;

  updatedAt: string;

  lastUsedAt?: string | null | undefined;

  isAlgoliaManaged?: boolean | undefined;
};
