// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { AnthropicProviderInput } from './anthropicProviderInput';
import type { AzureOpenAIProviderInput } from './azureOpenAIProviderInput';
import type { BaseProviderInput } from './baseProviderInput';
import type { OpenAICompatibleProviderInput } from './openAICompatibleProviderInput';
import type { OpenAIProviderInput } from './openAIProviderInput';

export type ProviderInput =
  | OpenAIProviderInput
  | AzureOpenAIProviderInput
  | OpenAICompatibleProviderInput
  | BaseProviderInput
  | AnthropicProviderInput;
