// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type SecretKeyResponse = {
  id: string;

  name: string;

  value: string;

  createdAt: string;

  updatedAt: string;

  lastUsedAt: string | null;

  isDefault?: boolean | undefined;

  agentIds: Array<string>;
};
