// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Secret key creation payload.
 */
export type SecretKeyCreate = {
  /**
   * The name of the secret key.
   */
  name: string;

  /**
   * List of agent IDs this secret key is associated with.
   */
  agentIds?: Array<string> | undefined;
};
