// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { StringArrayParamConstraint } from './stringArrayParamConstraint';

/**
 * A string array search parameter with exposure control, constraints, and merge behavior.
 */
export type StringArrayParam = {
  exposed: boolean;

  _default?: Array<string> | null | undefined;

  constraint?: StringArrayParamConstraint | null | undefined;

  merge?: boolean | null | undefined;
};
