// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * Model for tool invocation in a Message.
 */
export type ToolInvocationV4 = {
  toolCallId: string;

  toolName: string;

  args?: { [key: string]: any } | undefined;

  result?: { [key: string]: any } | undefined;

  step?: number | undefined;

  state?: string | undefined;

  providerOptions?: { [key: string]: any } | undefined;

  requiresApproval?: boolean | undefined;

  description?: string | undefined;

  argsHash?: string | undefined;
};
