// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

/**
 * A tool invocation in a message.
 */
export type ToolInvocationV4 = {
  toolCallId: string;

  toolName: string;

  args?: { [key: string]: any } | undefined;

  result?: { [key: string]: any } | null | undefined;

  step?: number | null | undefined;

  state?: string | null | undefined;

  providerOptions?: { [key: string]: any } | null | undefined;

  requiresApproval?: boolean | null | undefined;

  description?: string | null | undefined;

  argsHash?: string | null | undefined;
};
