// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { LocationItemUnion } from './locationItemUnion';

export type ValidationError = {
  loc: Array<LocationItemUnion>;

  msg: string;

  type: string;

  input?: any | null | undefined;

  ctx?: Record<string, unknown> | undefined;
};
