// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type BaseResponse = {
  /**
   * HTTP status code.
   */
  status?: number;

  /**
   * Details about the response, such as error messages.
   */
  message?: string;
};
