// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import type { Facet } from './facet';

/**
 * Configuration of an Algolia index for Query Suggestions.
 */
export type SourceIndex = {
  /**
   * Name of the Algolia index (case-sensitive) to use as source for query suggestions.
   */
  indexName: string;

  /**
   * If true, Query Suggestions uses all replica indices to find popular searches. If false, only the primary index is used.
   */
  replicas?: boolean | undefined;

  /**
   * Analytics tags for filtering the popular searches. For more information, see [Segment your analytics data](https://www.algolia.com/doc/guides/search-analytics/guides/segments).
   */
  analyticsTags?: Array<string> | null | undefined;

  /**
   * Facets to use as top categories with your suggestions.  If provided, Query Suggestions adds the top facet values to each suggestion.
   */
  facets?: Array<Facet> | null | undefined;

  /**
   * Minimum number of hits required to be included as a suggestion.  A search query must at least generate `minHits` search results to be included in the Query Suggestions index.
   */
  minHits?: number | undefined;

  /**
   * Minimum letters required to be included as a suggestion.  A search query must be at least `minLetters` long to be included in the Query Suggestions index.
   */
  minLetters?: number | undefined;

  /**
   * Facets used for generating query suggestions from facet values.  For example, if you set `generate: [\"color\", \"brand\"]`, combinations from the facet values are added as query suggestions, such as \"blue adidas\", \"red adidas\", \"blue nike\", \"red nike\", etc.  You can include nested lists.
   */
  generate?: Array<Array<string>> | null | undefined;

  /**
   * Algolia indices with popular searches to use as query suggestions.  Records of these indices must have these attributes:  - `query`: search query which will be added as a suggestion - `count`: measure of popularity of that search query  For example, you can export popular searches from an external analytics provider, such as Google Analytics or Adobe Analytics, and feed this data into an Algolia index. You can use this index to generate query suggestions until your Algolia Analytics has collected enough data.
   */
  external?: Array<string> | null | undefined;
};
