// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type SourceIndexExternal = {
  /**
   * The suggestion you would like to add.
   */
  query: string;

  /**
   * The measure of the suggestion relative popularity.
   */
  count: number;
};
