// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

export type SuccessResponse = {
  /**
   * The status code.
   */
  status: number;

  /**
   * Message of the response.
   */
  message: string;
};
